# Generated by Django 2.2.6 on 2019-11-12 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 12, 11, 3, 59, 900431))),
                ('updated', models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 12, 11, 3, 59, 900504))),
                ('preparation_time', models.SmallIntegerField()),
                ('votes', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
