# Generated by Django 2.2.6 on 2019-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20191112_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(default='Opis przepisu'),
            preserve_default=False,
        ),
    ]
